Colecoes/Models/Item.cs
using Colecoes.Interfaces;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;

namespace Colecoes.Models
{
    public class Item : item, IOperacaoDB<item>
    {
        private Entities db;

        public Item()
        {
            db = new Entities();
        }

        public bool Create(item model)
        {
            try
            {
                db.item.Add(model);
                db.SaveChanges();
                return true;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public bool Edit(item model)
        {
            try
            {
                db.Entry(model).State = EntityState.Modified;
                db.SaveChanges();
                return true;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public bool Delete(int id)
        {
            try
            {
                item model = GetRegisterById(id);
                if (model == null)
                {
                    throw new Exception("Registro não localizado");
                }

                db.Entry(model).State = EntityState.Deleted;
                db.SaveChanges();
                return true;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public item GetRegisterById(int id)
        {
            try
            {
                return db.item.Find(id);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public IEnumerable<item> GetAllRegisters()
        {
            try
            {
                var itemList = db.item.DefaultIfEmpty();
                return itemList;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

Colecoes/Controllers/ItemController.cs
using Colecoes.Models;
using System;
using System.Linq;
using System.Web.Mvc;

namespace Colecoes.Controllers
{
    public class ItemController : Controller
    {
        private Entities db = new Entities();

        // GET: Item
        public ActionResult Index()
        {
            return View(db.item.ToList());
        }

        // GET: Item/Details/5
        public ActionResult Details(int id)
        {
            Item objItem = new Item();
            item model = objItem.GetRegisterById(id);

            if (model == null)
            {
                return HttpNotFound();
            }

            return View(model);
        }

        // GET: Item/Create
        public ActionResult Create()
        {
            PreencherDropDownList();
            Item model = new Item();

            return View(model);
        }

        public ActionResult CreateForParent()
        {
            PreencherDropDownList();
            Item model = new Item();

            return View("Create", model);
        }

        // POST: Item/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(item model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Item objItem = new Item();
                    objItem.Create(model);

                    return RedirectToAction("Index");
                }
                else
                {
                    PreencherDropDownList(model.idColecao);
                    return View(model);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                PreencherDropDownList(model.idColecao);
                return View(model);
            }
        }

        // GET: Item/Edit/5
        public ActionResult Edit(int id)
        {
            Item objItem = new Item();
            item model = objItem.GetRegisterById(id);

            if (model == null)
            {
                return HttpNotFound();
            }

            PreencherDropDownList(model.colecao.idColecaoPai, model.idColecao);
            return View(model);
        }

        public ActionResult EditForParent(int id)
        {
            Item objItem = new Item();
            item model = objItem.GetRegisterById(id);

            if (model == null)
            {
                return HttpNotFound();
            }

            PreencherDropDownList(model.idColecao);//Nesse caso não quero saber se tem filho. Estou editando diretamente
            return View("Edit", model);
        }

        // POST: Item/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(item model)
        {
            Item objItem = new Item();
            try
            {
                if (ModelState.IsValid)
                {
                    objItem.Edit(model);

                    return RedirectToAction("Index");
                }
                else
                {
                    PreencherDropDownList(model.idColecao);
                    return View(model);
                }
            }
            catch (Exception ex)
            {
                //Aqui recupero o registro original, para ver se ele não foi alterado ou excluido
                item modelRec = objItem.GetRegisterById(model.idItem);

                if (modelRec == null)
                {
                    ModelState.AddModelError("", "Registro Excluído");
                }
                else
                {
                    ModelState.AddModelError("", ex.Message);
                    model = modelRec;
                }

                PreencherDropDownList(model.idColecao);
                return View(model);
            }
        }

        // GET: Item/Delete/5
        public ActionResult Delete(int id)
        {
            Item objItem = new Item();
            item itemReg = objItem.GetRegisterById(id);

            if (itemReg == null)
            {
                return HttpNotFound();
            }
            return View(itemReg);
        }

        // POST: /Tipo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Item objItem = new Item();
            try
            {
                objItem.Delete(id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                item model = objItem.GetRegisterById(id);
                ModelState.AddModelError("", ex.Message);
                return View(model);
            }
        }

        #region Operacoes
        [HttpGet]
        public ActionResult LancarLoteItem()
        {
            PreencherDropDownList();
            return View(new item());
        }

        [HttpPost]
        public ActionResult LancarLoteItem(item model, int repeticoes)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Item objItem = new Item();
                    int codigoInicial = 0;
                    string codigoStr = string.Empty;
                    //Tenta converter para inteiro o código do item, se não conseguir significa que o código é uma string não numeral.
                    //Então atribui o valor do cógido a string ao codigoStr
                    if (!int.TryParse(model.Codigo, out codigoInicial))
                    {
                        codigoStr = model.Codigo;
                    }

                    for (int i = 0; i < repeticoes; i++)
                    {
                        model.Codigo = codigoStr + codigoInicial.ToString();
                        objItem.Create(model);
                        codigoInicial++;
                    }
                }
                else
                {
                    PreencherDropDownList(model.idColecao);
                    return View(model);
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                PreencherDropDownList(model.idColecao);
                ModelState.AddModelError("", ex.Message);
                return View(model);
            }
        }
        #endregion

        #region Funções Suporte
        public  JsonResult GetFilhos(int id)
        {
            Colecao objColecao = new Colecao();
            SelectList selectList =  new SelectList(objColecao.GetRegistersByParent(id), "idColecao", "ColecaoNome");

            return Json(new { lista = selectList }, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Preencher as ddl's de tipo e colecao pai
        /// </summary>
        /// <param name="idColecaoPai">Valor que deve vir selecionado do ddl colecao(opcional)</param>
        private void PreencherDropDownList(int? idColecaoPai = null, int? idColecao = null)
        {
            ViewBag.ColecaoPai = new SelectList(db.colecao, "idColecao", "ColecaoNome", idColecaoPai);
            ViewBag.Colecao = new SelectList(db.colecao.Where(c => c.idColecaoPai == idColecaoPai), "idColecao", "ColecaoNome", idColecao);
            //ViewBag.Tipo = new SelectList(db.tipo, "idTipo", "TipoNome", idColecaoPai);
            //ViewBag.idImagemCapa = new SelectList(db.arquivo, "idArquivo", "ArquivoCaminho", colecao.idImagemCapa);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        #endregion
    }
}

Colecoes/Views/Item/Create.cshtml
@model Colecoes.item

@{
    ViewBag.Title = "Create";
}

@Html.Partial("EditForm")

Colecoes/Views/Item/Delete.cshtml
@model Colecoes.item

@{
    ViewBag.Title = "Delete";
}

<h3>Deseja excluir o registro?</h3>

@Html.Partial("Details")

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-default" /> |
        @Html.ActionLink("Back to List", "Index")
    </div>
}

Colecoes/Views/Item/Details.cshtml
@model Colecoes.item

@{
    string actionName = ViewContext.RouteData.Values["action"].ToString().ToLower();
    if (actionName != "delete")
    { ViewBag.Title = "Details"; }
}

<h2>@ViewBag.Title</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ItemNome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemNome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Codigo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ValorItem)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ValorItem)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.arquivo.ArquivoCaminho)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.arquivo.ArquivoCaminho)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.colecao.ColecaoNome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.colecao.ColecaoNome)
        </dd>

    </dl>
</div>

@if (actionName != "delete")
{
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.idItem }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Colecoes/Views/Item/Edit.cshtml
@model Colecoes.item

@{
    ViewBag.Title = "Edit";
}

@Html.Partial("EditForm")

Colecoes/Views/Item/EditForm.cshtml
@model Colecoes.item
@{
    string actionName = ViewContext.RouteData.Values["action"].ToString().ToLower();
    Dictionary<string, string> caption = new Colecoes.Operacoes.CaptionGeneration().ReadCaptionFile();
}

@using (Html.BeginForm((string)@ViewBag.Title, "Item", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)
        @if (actionName == "edit")
        {
            @Html.HiddenFor(model => model.idItem)
        }
        @if (actionName.Contains("parent"))
        {
            <div class="form-group">
                @Html.LabelFor(model => model.idColecao, caption["idColecao"], htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("idColecao", (IEnumerable<SelectListItem>)ViewBag.ColecaoPai, "Selecione", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.idColecao, "", new { @class = "text-danger" })
                </div>
            </div>
        }
        else
        {
            <div class="form-group">
                @Html.Label(caption["idColecaoPai"], new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("idColecaoPai", (IEnumerable<SelectListItem>)ViewBag.ColecaoPai, "Selecione", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.idColecao, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.idColecao, caption["idColecao"], htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("idColecao", (IEnumerable<SelectListItem>)ViewBag.Colecao, "Selecione", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.idColecao, "", new { @class = "text-danger" })
                </div>
            </div>
        }

        <div class="form-group">
            @Html.LabelFor(model => model.idLocalArquivo, caption["ArquivoCaminho"], htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("Arquivo", null, new { @class = "form-control", type = "file" })
                @Html.ValidationMessageFor(model => model.idLocalArquivo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label(caption["ItemNome"], htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemNome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemNome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label(caption["Codigo"], htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label(caption["Descricao"], htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label(caption["ValorItem"], htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ValorItem, null, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ValorItem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script type="text/javascript">
    $("#Arquivo").on("change", function () {
        var a = "nome";
    })
    var urlpath = "@Url.Action("GetFilhos")";
</script>
<script src="~/Scripts/item.js"></script>

Colecoes/Views/Item/Index.cshtml
@model IEnumerable<Colecoes.item>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ItemNome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Codigo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ValorItem)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.arquivo.ArquivoCaminho)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.colecao.ColecaoNome)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ItemNome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Codigo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descricao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ValorItem)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.arquivo.ArquivoCaminho)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.colecao.ColecaoNome)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.idItem }) |
            @Html.ActionLink("Details", "Details", new { id=item.idItem }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.idItem })
        </td>
    </tr>
}

</table>

Colecoes/Views/Item/LancarLoteItem.cshtml
@model Colecoes.item

@{
    ViewBag.Title = "Lancar Itens em Lote";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>item</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.LabelFor(model => model.idColecao, "idColecao", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idColecao", (IEnumerable<SelectListItem>)ViewBag.Colecao, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idColecao, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.idLocalArquivo, "idLocalArquivo", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("idLocalArquivo", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.idLocalArquivo, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.ItemNome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemNome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemNome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Código Inicial", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ValorItem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ValorItem, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ValorItem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Repetições", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("repeticoes", 1, new { @class = "form-control" , type="number"})
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lançar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>